### ISSUE TITLE
Improve tooling overview page and tables

### ISSUE THREAD

**Issue by philipwindecker** [asam-ev/asam-project-guide#25]
Make an improved suggestion regarding the tooling introduction page and its tables.

* https://github.com/asam-ev/asam-project-guide/blob/main/doc/modules/getting-started/pages/tools-overview.adoc
* https://github.com/asam-ev/asam-project-guide/blob/main/doc/modules/tooling/partials/list-of-tools.adoc

The idea is to highlight infrastructure vs. supported/recommended tools and improve descriptions.

**Comment by 9h03n1x** [comment]
I create a pull request for where I added a suggestion on how to improve this.

**Comment by philipwindecker** [comment]
Is this issue done? Or do you still want to contribute more to it on top of the pull request?
