### ISSUE TITLE
Content feedback: Change landing page "Working on the Project Guide"

### ISSUE THREAD

**Issue by philipwindecker** [asam-ev/asam-project-guide#50]
# Prerequisites

This is in regards to:

- [ ] Title
- [ ] Content: Text
- [x] Content: Image(s)
- [x] Formatting
- [ ] Location in Project Guide
- [ ] Obsolete

# Subject
Change the style and setup of the landing page of the module "project-guide".

# Section
nA

# Description
![image](https://user-images.githubusercontent.com/95633467/149976263-3f2e15db-353f-4a97-bd4f-30c13c38f618.png)

The current landing page for Working on the Project Guide is quite text-heavy and hard to read.
It states its intentions but is not accessible enough for new people unfamiliar with its structure.

# Suggestion
I suggest adding icons or graphics to make the structure and its content more accessible and easy-to-understand.

| | |
|---|---|
| URL | https://asam-ev.github.io/asam-project-guide/asamprojectguide/project-guide/main.html |
| Page | Working on the Project Guide |
| Module | project-guide |

**Comment by philipwindecker** [comment]
New version:
![image](https://user-images.githubusercontent.com/95633467/150379632-7f710c8d-2b33-4e6c-bc7b-a6effe46f74e.png)

**Comment by 9h03n1x** [comment]
check if the table width can be limited so the table looks a bit nice

**Comment by philipwindecker** [comment]
![image](https://user-images.githubusercontent.com/95633467/154035448-7af608f4-5453-49ca-81b7-b3d087c57050.png)
New version

**Comment by 9h03n1x** [comment]
reviewed and accepted
