### ISSUE TITLE
Content feedback: Add missing macros

### ISSUE THREAD

**Issue by philipwindecker** [asam-ev/asam-project-guide#58]
# Prerequisites

This is in regards to:

- [ ] Title
- [x] Content: Text
- [ ] Content: Image(s)
- [ ] Formatting
- [ ] Location in Project Guide
- [ ] Obsolete

# Subject
Add missing macro definitions and update existing ones

# Section
tbd

# Description
The following macros are missing:
- role-related
- autonav

# Suggestion
Add description pages for each missing macro and check to update existing ones based on Antora extension solution.

| | |
|---|---|
| URL | https://asam-ev.github.io/asam-project-guide/asamprojectguide/project-guide/special-macros.html |
| Page | Custom ASAM Antora Macros |
| Module | project-guide |

**Comment by philipwindecker** [comment]
See also #43

**Comment by 9h03n1x** [comment]
Please add a link or a example how the complete site.yml would look like

**Comment by 9h03n1x** [comment]
Subpage: 
pages, reference, related: add a screenshot on the final result or improve description on the result of the macro

role_related: add description to example
autonav: add how to use parameters,

**Comment by philipwindecker** [comment]
Discussed topics are fixed in Project Guide and can be reviewed again.
