### ISSUE TITLE
Create project boards for organizing issues in GitHub

### ISSUE THREAD

**Issue by philipwindecker** [asam-ev/asam-project-guide#59]
See https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards

This requires to be a member of the organization.

**Comment by stefancyliax** [comment]
Added you to Org. Should be fixed now.

**Comment by philipwindecker** [comment]
Currently not (yet) possible. I see the option in the configuration of the project, but have no rights to change it.
Maybe this is sth only an admin can do?

**Comment by stefancyliax** [comment]
Sorry. Did miss the option to enable projects for org and repos. Now enabled. Please try again.

**Comment by philipwindecker** [comment]
Project set up, ready for review

**Comment by stefancyliax** [comment]
looking great!
